FROM php:7.4-fpm

# Set working directory
RUN mkdir /app
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
  build-essential \
  libzip-dev \
  libpng-dev \
  libonig-dev \
  libjpeg62-turbo-dev \
  libfreetype6-dev \
  locales \
  zip \
  jpegoptim optipng pngquant gifsicle \
  vim \
  unzip \
  git \
  curl \
  supervisor \
  cron

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg

RUN docker-php-ext-install gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
  composer config -g repos.packagist composer https://packagist.org
  # && \
  # composer global require hirak/prestissimo

# Copy supervisord conf
COPY supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Crontab
COPY cron/scheduler /etc/cron.d/scheduler
RUN crontab /etc/cron.d/scheduler

# Expose port 9000 and start supervisor: php-fpm server & worker
EXPOSE 9000

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
