version: "3.8"

services:
  nginx:
    container_name: san-nginx
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - 8000:80
    volumes:
      - ./:/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: san-php
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
    volumes:
      - ./:/app
      - ./docker/php/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
    working_dir: /app
    links:
      - mysql

  mysql:
    container_name: san-mysql
    image: mysql:5.7
    volumes:
      - san-mysql-store:/var/lib/mysql
      # - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=san
      - MYSQL_USER=san
      - MYSQL_PASSWORD=san
      - MYSQL_ROOT_PASSWORD=san
    ports:
      - 3333:3306

volumes:
  san-mysql-store:
